name: Workflow Demo

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Echo ACCESS_ID
      run: echo {{ var.ACCESS_ID }}
